#ifndef DEF_TRIVIALPLUGIN_DEFINITIONS_H
#define DEF_TRIVIALPLUGIN_DEFINITIONS_H

//MainWindow  - MainMenu
#define AG_MMENU_TRIVIALMESSAGE     950

//MenuIcons
#define MNI_TRIVIALPLUGIN_MESSAGE   "trivialpluginMessage"

#endif //DEF_TRIVIALPLUGIN_DEFINITIONS_H
